# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24506b2e4dac07caed6f44001c4c6fb4f7707825ae4b472e518fd2a8753173fc35b5f5b3b3e78b2b31db79c485d5ecd6cd62e00cd8749c911acd7f050dadac03

test:
  secret_key_base: 6a90190fdbf7685297ee3d2f8e8e23475a96639124380b3e0bac1640e87eead0ff1a48007637208a28ffeab010c523e938cb820d3ee70cd2985c48aec2818e73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
